apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: josiah-project
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Example Project
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc

