apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
spec:
  destination:
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: infrastructure
    repoURL: 'https://github.com/jcdenny/local-kubernetes.git'
    targetRevision: HEAD
  project: josiah-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true